### ISSUE TITLE
BUG NO INÍCIO

### ISSUE THREAD

**Issue by drsmithbr** [cryptotwinsbr/spacecrypto-bot#31]
O bot trava quando aparece o "erro de login" na conexão da wallet, e esse bug sempre ocorre aqui.

**Comment by vini-novais** [comment]
Tenta mudar as imagens do sign da metamask.

**Comment by cryptotwinsbr** [comment]
Fala drsmithbr, 
Baixe a ultima versão disponivel aqui no repositorio "v1.06" e de uma olhada nesse nosso ultimo ultimo video, estamos explicando certinho todos os passos para executar o bot 100%
https://www.youtube.com/watch?v=gJkrN4Zr9Ec

Se te ajudou da aquela força para os devs para trazermos sempre mais melhorias! 

Chave pix: 5f3d220c-a2a3-4db2-bfb2-30ae0533e240
Metamask wallet (BNB/SPG/BUSD/BCOIN): 0x73933b679F940ea7352c3895852501e3044FE855

**Comment by drsmithbr** [comment]
> Fala drsmithbr, Baixe a ultima versão disponivel aqui no repositorio "v1.06" e de uma olhada nesse nosso ultimo ultimo video, estamos explicando certinho todos os passos para executar o bot 100% https://www.youtube.com/watch?v=gJkrN4Zr9Ec
> 
> Se te ajudou da aquela força para os devs para trazermos sempre mais melhorias!
> 
> Chave pix: 5f3d220c-a2a3-4db2-bfb2-30ae0533e240 Metamask wallet (BNB/SPG/BUSD/BCOIN): 0x73933b679F940ea7352c3895852501e3044FE855



> 

Opa irmao, a atualização realmente resolveu esse bug, muito obrigado!
