### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by scorpio9527** [cryptotwinsbr/spacecrypto-bot#36]
when I pip install it shows

Collecting MouseInfo==0.1.3
  Using cached MouseInfo-0.1.3.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting mss==6.1.0
  Using cached mss-6.1.0-py3-none-any.whl (76 kB)
Collecting numpy==1.21.4
  Using cached numpy-1.21.4-cp310-cp310-macosx_10_9_x86_64.whl (17.0 MB)
Collecting opencv-python==4.5.4.60
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/fe/0a/96e00caf7a4d9ce79c8eeac1ae3880833e11913e5719a85b259103bcb1c6/opencv_python-4.5.4.60-cp310-cp310-macosx_11_0_x86_64.whl
  
seems can't collecting opencv-python++4.5.4.60

What can I do?

**Comment by cryptotwinsbr** [comment]
Helllo scorpio9527,

Try to reinstall the python with another version and execute this command again.

To maintain the improvments and this auto click bot free, please help me with any value, have fun :)

Chave pix: 5f3d220c-a2a3-4db2-bfb2-30ae0533e240
Metamask wallet (BNB/SPG/BUSD/BCOIN): 0x73933b679F940ea7352c3895852501e3044FE855
