### ISSUE TITLE
Ir somente até o BOSS 7

### ISSUE THREAD

**Issue by glafaete10** [cryptotwinsbr/spacecrypto-bot#37]
Queria saber se eu consigo configurar o bot para ir somente ate o boss 7, e assim que derrota-lo, dar surrender no boss 8 e começar o ciclo novamente ?

**Comment by cryptotwinsbr** [comment]
Fala glafaete10, 

Sim você consegue, basta apenas acessar o arquivo settings.yaml e alterar o parametro  "boss_surrender: 8"

Se te ajudou da aquela força para os devs para trazermos sempre mais melhorias!

Chave pix: 5f3d220c-a2a3-4db2-bfb2-30ae0533e240
Metamask wallet (BNB/SPG/BUSD/BCOIN): 0x73933b679F940ea7352c3895852501e3044FE855

**Comment by glafaete10** [comment]
Boa, deu certo o surrender no boss 8, porem temos um problema, ao voltar para o boss 1, as naves comuns conseguem chegar novamente somente ao boss 6. Fazendo a troca de naves no boss 6, as novas naves vão para o boss 7 com o bot as informando que é o boss 1, chegando no bos 8 essas novas naves não dão surrender porque no bot esta marcando que é o boss 2. Uma forma de resolver isso, seria buscar pela imagem boss 8 para dar surrender, que sempre que realmente estiver no boss 8 daria o surrender... Tem como modificar isso aqui nesse bot ou teria alguma outra forma de sempre dar surrender no boss desejado sem problemas ?
